name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build example chip
        uses: ./
        with:
          sources: test/main.c
          chip-json: test/chip.json

      - name: Show dist
        run: |
          ls -lah dist
          file dist/chip.wasm || true
